Repository canonical/netplan.io, pull requests merged in 2020-03, with the labels that each got.

#78 Multistage builds for netplan.io
  .dockerignore
  Dockerfile
  nginx.conf
Labels: Review: Code needed, Review: QA needed

#80 Github action to run docker image
  .github/workflows/tests.yml
Labels: Review: Code +1

#83 Replace sass-lint with stylelint
  .sass-lint.yml
  .stylelintrc
  _sass/main.scss
  package.json
  run
  yarn.lock
Labels: Review: Code +1, Review: QA +1
