Repository canonical/netplan.io, pull requests merged in 2020-05, with the labels that each got.

#88 Update the reference section, add an SR-IOV example
  examples.md
  reference.md
Labels: Review: QA +1

#90 Add locks files
  Gemfile.lock
  yarn.lock
Labels: Review: QA +1

#91 Update the reference page again with the latest doc updates.
  reference.md
Labels: Review: Code +1, Review: QA +1

#92 Remove the 'requires feature' mentions for both modems: and SR-IOV
  reference.md
Labels: Docs 📚

#93 design: Delete 'netplan config show' reference
  design.md
Labels: Docs 📚, Review: Code +1
