Repository canonical/netplan.io, pull requests merged in 2022-01, with the labels that each got.

#205 Switch to using the secure version of watch-cli
  package.json
  yarn.lock
Labels: Review: QA +1

#212 Fix 404
  src/404.html
  src/500.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#214 Add u-hide--small to TOC
  src/404.html
  src/500.html
  src/design.md
  src/faq.md
  src/index.html
  src/reference.md
  src/troubleshooting.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#215 Fix complex example indentation
  src/design.md
Labels: Review: Code +1, Review: QA +1
